site_name: Tips and tricks
site_url: https://linkdotnet.github.io/tips-and-tricks/
site_description: A collection of tips and tricks with smaller code snippets and explanation.
docs_dir: docs
repo_name: linkdotnet/tips-and-tricks
repo_url: https://github.com/linkdotnet/tips-and-tricks
edit_uri: edit/main/docs/
theme: 
  name: material 
  font:
    text: Sora
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true
nav:
  - Array: array.md
  - Async / Await: async_await.md
  - Blazor: blazor.md
  - Collections: collections.md
  - Exceptions: exceptions.md
  - LINQ: linq.md
  - Misc: misc.md
  - Strings: strings.md
  - ValueTuple: valuetuple.md
  - Advanced:
    - advanced/index.md
    - ArrayPools to minimize allocations: advanced/arraypool.md
    - Boxing/Unboxing: advanced/boxing.md
    - Iterate through a List<T>: advanced/iterate_list.md
    - Lazy: advanced/lazy.md
    - SIMD: advanced/SIMD.md
    - Span: advanced/span.md
    - stackalloc: advanced/stackalloc.md
    - struct: advanced/struct.md
  - EF Core:
    - efcore/index.md
    - Don't track readonly entities: efcore/asnotracking.md
    - Define maximum length for strings: efcore/maxlength_strings.md
    - In Memory database with SQLite: efcore/in_memory_sqlite.md
    - SplitQuery: efcore/splitquery.md
  - NuGet:
    - nuget/index.md 
    - Use floating versioning: nuget/floating_versioning.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/steven-giesel/
    - icon: fontawesome/brands/github
      link: https://github.com/linkdotnet
    - icon: fontawesome/solid/rss
      link: https://steven-giesel.com/ 


copyright: 2022 <a href="https://github.com/linkdotnet">Steven Giesel</a>.