site_name: Tips and tricks
site_url: https://linkdotnet.github.io/tips-and-tricks/
site_description: A collection of tips and tricks with smaller code snippets and explanation.
docs_dir: docs
repo_name: linkdotnet/tips-and-tricks
repo_url: https://github.com/linkdotnet/tips-and-tricks
edit_uri: edit/main/docs/
theme: 
  name: material 
  font:
    text: Sora
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:pymdownx.emoji.twemoji
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true
nav:
  - Async / Await: async_await.md
  - Blazor: blazor.md
  - Collections: collections.md
  - Exceptions: exceptions.md
  - Misc: misc.md
  - Strings: strings.md
  - Advanced:
    - advanced/index.md
    - stackalloc: advanced/stackalloc.md

copyright: 2022 <a href="https://github.com/linkdotnet">Steven Giesel</a>.